<?php include __DIR__.'/header.phtml'; ?>

<main class="container-fluid pt-5">
    <div class="row w-75 mx-auto">
        <h2 class="my-4">Date du trajet</h2>
        <section class="col-8">
            <div class="d-flex justify-content-between border border-3 border-success rounded m-2 p-2 shadow bg-light-subtle">
                <p><strong>Marseille</strong>H de départ<i class="bi bi-dash-lg"></i><strong>Nice</strong>H d'arrivée <br> Durée du trajet</p>
                <p> Nombre de place restance</p> 
            </div>

            <div class="border border-3 border-success rounded m-2 p-2 shadow bg-light-subtle">
                <div class="d-flex">
                         <p class="px-2">Photo</p> <p class="px-2"> Pseudo <br> Note <i class="bi bi-star"></i></p>
                </div>
                <hr>
                <div>
                    <strong><i class=" px-1 bi bi-calendar"></i>
                        Votre réservation sera confirmée lorsque le conducteur acceptera votre demande <br>
                    </strong>

                    <strong><i class="px-1 bi bi-car-front"></i> Modele de la voiture  <button class="btn btn-success px-2"><i class="bi bi-car-front"></i><i class="bi bi-leaf"></i></button></strong>
                </div>

                <hr>

                <div>
                    <h4>Preferences du conducteur</h4>
                    <ul>
                        <li>truc</li>
                    </ul>
                </div>

            </div>

               <article class="avis  border border-3 border-success rounded m-2 p-2 shadow bg-light-subtle">
                    <h4> Dernier Avis</h4>
                    <ul>
                        <li>
                            <div>avi 1</div>
                        </li>
                    </ul>
                </article>
        </section>

        <aside class="col-4 ">
            <div class="bg-light-subtle d-flex justify-content-between border border-3 border-success rounded m-2 p-2 shadow">
                <p>Nombre passager</p>
                <p>prix <br>credit</p>
            </div>

            <div class="text-center">
                <button type="button" class=" btn btn-lg btn-success shadow" data-bs-toggle="modal" data-bs-target="#Modalconfirmtrajet">Participer</button>
            </div>
        </aside>
    </div>

    <!-- contenu de la modale -->
     <div class="modal fade" id="Modalconfirmtrajet" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="ModalLabel">Confirmation</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Souhaitez vous dépenser 20 credits pour ce trajet ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                    <button type="button" class="btn btn-success">Poursuivre</button>
                </div>
            </div>
        </div>
    </div>


</main>


<?php include __DIR__ . '/footer.phtml'; ?>
