   <footer class="py-3 bg-dark border-bottom border-body " data-bs-theme="dark">
        <div class="container-xl">
        <p class="navbar-text mb-0 text-center text-body-secondary ">Ecoride@gmail.fr mentions legales</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>