<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $titlea; ?></title>
    <link rel="stylesheet" href="css/scss/main.css">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
   <link rel="stylesheet" href="css/admstyle.css">
   <script defer src="js/main.js"></script>
   
</head>
<body class="min-vh-100 grd">
    <header class="header_nav" >
     <nav class="navbar  bg-dark border-bottom border-body navbar-expand-lg" data-bs-theme="dark">
        <div class="container-fluid" id="navbare">
            <a href="Accueil.php"><img class="navbar-brand" src="img/EcoRide.png"  alt="Logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class=" collapse navbar-collapse " id="navbarSupportedContent">

             

                <ul class="navbar-nav ">
                  <li class="nav-item dropdown px-5">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="bi bi-person-circle"></i>Employé
                        </a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="employeesign.php"><i class="bi bi-person-add"></i> Connexion</a></li>
                          <li><a class="dropdown-item" href="employeeprofile.php"><i class="bi bi-person"></i> Espace perso</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="admin.php">Admin</a></li>
                        </ul>
                    </li>
                    
                 

                </ul>
            </div>
        </div>
      </nav>
    </header>