<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $titlea; ?></title>
   <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="css/scss/main.css">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
   <link rel="stylesheet" href="css/style.css">
   <script type="module" src="js/main.js"></script>

</head>
<body class="min-vh-100 grd">
    <header class="header_nav" >
     <nav class="navbar navbar-expand-lg">
        <div class="container-fluid d-flex "  id="navbare">
           <div class="me-auto"><a href="Accueil.php"><img class="navbar-brand" src="img/EcoRide.png"  alt="Logo"></a></div> 
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <!-- <form class="d-flex" role="search">
            <div class="input-group">
                <input type="date" id="trip_date" name="search_trip" class="form-control">
                <select class="form-select" id="inputGroupSelect04" aria-label="select">
                  <option selected>Départ</option>
                  <option value="1">Marseille</option>
                  <option value="2">Bordeaux</option>
                  <option value="3">Lille</option>
                  <option value="4">Strasbourg</option>
                </select>
                <select class="form-select" id="inputGroupSelect04" aria-label="select">
                  <option selected>Arrivée</option>
                  <option value="1">Marseille</option>
                  <option value="2">Bordeaux</option>
                  <option value="3">Lille</option>
                  <option value="4">Strasbourg</option>
                </select>
                <button class="btn" type="button"><i class="bi bi-arrow-right-square"></i></button>
            </div>
            </form> -->
            <div class=" collapse navbar-collapse " id="navbarSupportedContent">

             

                <ul class="navbar-nav ">
                  <li class="nav-item dropdown px-5">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="bi bi-person-circle"></i>
                        </a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="inscriptions.php"><i class="bi bi-person-add"></i>  M'INSCRIRE</a></li>
                          <li><a class="dropdown-item" href="connexion.php"><i class="bi bi-person"></i> ME CONNECTER</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="compte.php">Mon compte</a></li>
                        </ul>
                    </li>

                    <li class="nav-item px-5">
                      <a class="nav-link " aria-current="page" href="trajet.php">
                      <i class="bi bi-car-front-fill"></i>  
                      TRAJETS</a>
                    </li>
                    
                    <li class="nav-item px-5">
                      <a class="nav-link" href="contact.php">
                        <i class="bi bi-envelope-open"></i>
                        CONTACT
                      </a>
                    </li>
                    
                 

                </ul>
            </div>
        </div>
      </nav>
    </header>