<?php include __DIR__.'/header.phtml'; ?>

<main class="d-flex flex-column justify-content-around">


		<section class="mention">
			<div class="text-center ">
				<header>
					<h2 class="title-legal">
						Mentions légales
					</h2>
				</header>
				<div class="content-legal">
					<div class="align-baseline">
						<strong>Ecoride</strong>
						<br>
						<strong>SIRET :
						</strong>
						191 240 407 00111
						<br><br>
					</div>
					<div class="align-baseline">
						<strong>Adresse :
						</strong>
						1 rue de la paix Marcel paul,
						75017
						PARIS
					</div>
					<div class="align-baseline">
						<strong>Email :
						</strong>
						Ecoride@gmail.fr
					</div>
					<div class="align-baseline">
						<strong>Responsable de la publication :
						</strong>
						Jean Dupont
					</div>
					<div class="align-baseline">
						<strong>Créateur du site :
						</strong>
						Jean Dupont 
					</div>
					<div class="align-baseline">
						<br>
						<strong>Hébergement<br></strong>
					</div>
					<div class="align-baseline">
						HOSTINGER
						<br>
						dont le siège social est situé HOSTINGER INTERNATIONAL LTD, 61 Lordou Vironos Street, 6023 Larnaca, Chypre
					</div>
				</div>
			</div>
        </section>
	
</main>

<?php include __DIR__ . '/footer.phtml'; ?>
